version: '3'

services:
  deepseek-free-api:
    container_name: DP
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
      - DEEP_SEEK_CHAT_AUTHORIZATION=
      - PROXY_LIST=${PROXY_LIST:-[]}  # Добавляем переменную с пустым значением по умолчанию
      - PROXY_TIMEOUT=${PROXY_TIMEOUT:-20000}